name: Auto-merge PRs

on:
  pull_request_target:
    types: [opened, synchronize]
    paths:
      - 'Contributors.md'

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2

      - name: Verify PR modifies only Contributors.md
        id: check_files
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})

          echo "Changed files: $CHANGED_FILES"

          if [ "$CHANGED_FILES" == "Contributors.md" ]; then
            echo "only_contributors=true" >> $GITHUB_ENV
          else
            echo "only_contributors=false" >> $GITHUB_ENV
          fi

      - name: Merge PR
        id: merge_pr
        if: env.only_contributors == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              const response = await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                merge_method: "squash"
              });

              if (response.status === 200) {
                const gifs = [
                  'https://c.tenor.com/ZCq4SwgCfxAAAAAC/snoopy-peanuts.gif',
                  'https://c.tenor.com/Z0ojZS2kpO0AAAAC/milk-and-mocha-happy.gif',
                  'https://c.tenor.com/LffD4a8ET9AAAAAC/heart-celebrate.gif',
                  'https://c.tenor.com/HJ0iSKwIG28AAAAC/yes-baby.gif',
                  'https://c.tenor.com/4blWuIh5MIYAAAAC/baby-yoda.gif'
                ];

                const message = `
                  Hello @${context.payload.pull_request.user.login}, congratulations! 🎉
                  Your pull request has been merged successfully.
                  ![Celebration](${gifs[Math.floor(Math.random() * gifs.length)]})
                `;
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  body: message
                });
              }
            } catch (error) {
              core.setFailed(`Merge failed: ${error.message}`);
            }

      - name: Comment if PR not merged
        if: env.only_contributors != 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const filesChanged = process.env.CHANGED_FILES.split('\n').filter(file => file);
            const message = `
              Thank you for your pull request. This pull request contains changes to files that require a review:
              ${filesChanged.map(file => `- ${file}`).join('\n')}
            `;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: message
            });
